# Generated by Django 4.2.15 on 2024-08-25 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='is_vendor',
        ),
    ]
